Avoid name clashing no geom columns provided but existing the_geom
Fix for CDB_SetUp_PG_Federated_Table('server', 'schema', 'table', 'id)
when the table contains the_geom and/or the_geom_webmercator columns
but they are not part of the input.

Otherwise it fails with

    ERROR:  column "the_geom" specified more than once