Comment out suspected line
This may be causing the error

     ERROR:  could not compile PL/Python function "__cdb_fs_tcp_foreign_server_latency"
     DETAIL:  SyntaxError: invalid syntax (<string>, line 26)

when testing in PG12 + plpythonu3